export enum ApparelSunglassesColumns {
    LastUpdate = "updatedAt",
    UpdatedBy = "updatedBy",
    GTIN = "gtin",
    Status = "status",
    Designer = "designer",
    QcTeam = "qcTeam",
    MerchantsQc = "siteOpsQc",
    Priority = "priority",
    Calibration = "calibrationName",
    Tag = "Tag",
    BrandName = "brandname",
    BaseId = "baseId",
    ItemId = "itemId",
    LensWidth = "lensWidth",
    LensHeight = "lensHeight",
    LensBridge = "lensBridge",
    ArmLength = "armLength",
    ActualColor = "actualColor",
    Shape = "shape",
    PDPLink = "pdpLink",
    SidePNG = "sidePng",
    GLB = "glb",
    IOSCalibrated = "iosCalibrated"
}